'use client';

import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';

type Media = 'movie' | 'tv';
type Status = 'draft' | 'review' | 'published' | 'broken' | 'hidden';
type Item = { tmdb_id:number; media_type:Media; title?:string|null; title_th?:string|null; watch_url?:string|null; trailer_url?:string|null; provider?:string|null; notes?:string|null; section_slug?:string; status?:Status; poster_url?:string|null; rating?:number; year?:string; language?:string };
type Payload = { ok:boolean; links?:Item[]; meta?:{hasMore?:boolean}; error?:string };
type Form = { tmdb_id:string; media_type:Media; title:string; title_th:string; watch_url:string; trailer_url:string; section_slug:string; status:Status; provider:string; notes:string };

const sections = ['watch-ready','top-rated','popular','now-playing','series','thai','action','horror','comedy','korea','japan','china','documentary'];
const sources = ['all','top-rated','popular','now-playing','series','thai','action','horror','comedy','korea','japan','china','documentary'];
const cls = 'rounded-xl bg-white/10 px-3 py-2 text-sm text-white outline-none';
function token(v:string){return v.trim().replace(/^DOFREE_ADMIN_TOKEN\s*=\s*/i,'').trim();}
function name(i:Item){return i.title_th||i.title||`TMDB ${i.tmdb_id}`;}
function toForm(i:Item):Form{return{tmdb_id:String(i.tmdb_id),media_type:i.media_type,title:i.title||'',title_th:i.title_th||i.title||'',watch_url:i.watch_url||'',trailer_url:i.trailer_url||'',section_slug:i.section_slug||'watch-ready',status:i.watch_url?'published':i.status||'draft',provider:i.provider||'bunny',notes:i.notes||''};}

function Edit({item,form,setForm,onClose,onSave,saving}:{item:Item;form:Form;setForm:(f:Form)=>void;onClose:()=>void;onSave:(e:FormEvent)=>void;saving:boolean}){
 return <div className="fixed inset-0 z-50 overflow-auto bg-black/80 p-4 text-white"><form onSubmit={onSave} className="mx-auto max-w-2xl rounded-3xl bg-[#060606] p-5 ring-1 ring-white/10"><div className="flex gap-4"><img src={item.poster_url||''} className="h-40 w-28 rounded-xl object-cover bg-white/10"/><div className="flex-1"><p className="text-xs font-black text-[#e50914]">EDIT MOVIE</p><h2 className="mt-2 text-3xl font-black">{form.title_th||form.title||name(item)}</h2><p className="mt-2 text-xs text-white/50">TMDB {item.tmdb_id} • ★ {Number(item.rating||0).toFixed(1)} • {item.year||'-'}</p></div><button type="button" onClick={onClose} className="h-10 w-10 rounded-full bg-white/10 text-xl">×</button></div><div className="mt-5 grid gap-3"><input value={form.watch_url} onChange={e=>setForm({...form,watch_url:e.target.value,status:e.target.value.trim()?'published':form.status})} placeholder="ลิงก์รับชม" className={cls}/><input value={form.trailer_url} onChange={e=>setForm({...form,trailer_url:e.target.value})} placeholder="Trailer URL" className={cls}/><input value={form.title_th} onChange={e=>setForm({...form,title_th:e.target.value})} placeholder="ชื่อไทย" className={cls}/><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="ชื่ออังกฤษ" className={cls}/><select value={form.section_slug} onChange={e=>setForm({...form,section_slug:e.target.value})} className={cls}>{sections.map(s=><option key={s} value={s}>{s}</option>)}</select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})} className={cls}><option value="draft">draft</option><option value="review">review</option><option value="published">published</option><option value="broken">broken</option><option value="hidden">hidden</option></select><input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} placeholder="provider" className={cls}/><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="หมายเหตุ" className={cls}/></div><div className="mt-5 flex flex-wrap justify-end gap-2"><a href={form.watch_url||'#'} target="_blank" className={`rounded-xl bg-white/10 px-4 py-2 text-sm ${form.watch_url?'':'pointer-events-none opacity-40'}`}>เปิด Preview</a><button type="button" onClick={()=>setForm({...form,watch_url:'',status:'draft'})} className="rounded-xl bg-white/10 px-4 py-2 text-sm">ล้างลิงก์</button><button type="button" onClick={onClose} className="rounded-xl bg-white/10 px-4 py-2 text-sm">ยกเลิก</button><button disabled={saving} className="rounded-xl bg-[#e50914] px-5 py-2 text-sm font-black">{saving?'กำลังบันทึก':'บันทึก'}</button></div></form></div>;
}

export function AdminCatalogTable(){
 const [adminToken,setAdminToken]=useState(''); const [q,setQ]=useState(''); const [source,setSource]=useState('all'); const [status,setStatus]=useState('missing'); const [sort,setSort]=useState('rating'); const [items,setItems]=useState<Item[]>([]); const [offset,setOffset]=useState(0); const [hasMore,setHasMore]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [active,setActive]=useState<Item|null>(null); const [form,setForm]=useState<Form|null>(null); const limit=240;
 useEffect(()=>{const t=localStorage.getItem('dofree_admin_token')||''; if(t){setAdminToken(t); void load(0,false,t);}},[]);
 async function load(nextOffset=0,append=false,t=adminToken){const clean=token(t); if(!clean){setErr('ใส่ Admin Token ก่อน');return;} localStorage.setItem('dofree_admin_token',clean); setAdminToken(clean); setLoading(true); setErr(''); setMsg(''); try{const p=new URLSearchParams({q,source,media:'all',status,sort,limit:String(limit),offset:String(nextOffset)}); const r=await fetch(`/api/admin/catalog-lite?${p}`,{headers:{'x-admin-token':clean},cache:'no-store'}); const d=await r.json() as Payload; if(!r.ok||!d.ok)throw new Error(d.error||'โหลดไม่สำเร็จ'); const next=d.links||[]; setItems(old=>append?[...old,...next]:next); setOffset(nextOffset+next.length); setHasMore(Boolean(d.meta?.hasMore)); setMsg(`โหลด ${next.length} รายการ`);}catch(e){setErr(e instanceof Error?e.message:'โหลดไม่สำเร็จ');}finally{setLoading(false);}}
 async function save(e:FormEvent){e.preventDefault(); if(!form)return; setSaving(true); setErr(''); try{const r=await fetch('/api/admin/movie-links',{method:'POST',headers:{'content-type':'application/json','x-admin-token':token(adminToken)},body:JSON.stringify({...form,tmdb_id:Number(form.tmdb_id)})}); const d=await r.json() as Payload; if(!r.ok||!d.ok)throw new Error(d.error||'บันทึกไม่สำเร็จ'); setMsg('บันทึกแล้ว'); setActive(null); setForm(null); await load(0,false);}catch(e){setErr(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setSaving(false);}}
 function open(i:Item){setActive(i); setForm(toForm(i));}
 return <main className="min-h-screen bg-[#030303] p-4 text-white md:p-8"><a href="/" className="text-xs text-red-200/70">← กลับหน้าแรก</a><h1 className="mt-6 text-4xl font-black md:text-6xl">Admin Catalog</h1><div className="mt-6 grid gap-2 rounded-2xl bg-white/[0.04] p-3 md:grid-cols-[1fr_1fr_160px_160px_160px_auto]"><input type="password" value={adminToken} onChange={e=>setAdminToken(e.target.value)} placeholder="Admin Token" className={cls}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาหนัง" className={cls}/><select value={source} onChange={e=>setSource(e.target.value)} className={cls}>{sources.map(s=><option key={s} value={s}>{s}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className={cls}><option value="missing">ยังไม่มีลิงก์</option><option value="ready">พร้อมดู</option><option value="all">ทั้งหมด</option></select><select value={sort} onChange={e=>setSort(e.target.value)} className={cls}><option value="rating">คะแนนสูง</option><option value="newest">หนังใหม่</option><option value="popular">ยอดนิยม</option></select><button onClick={()=>load(0,false)} disabled={loading} className="rounded-xl bg-[#e50914] px-4 py-2 font-black">{loading?'โหลด':'ค้นหา'}</button></div>{msg?<p className="mt-3 rounded-xl bg-green-400/10 p-2 text-sm text-green-100">{msg}</p>:null}{err?<p className="mt-3 rounded-xl bg-red-500/10 p-2 text-sm text-red-100">{err}</p>:null}<div className="mt-5 grid grid-cols-3 gap-3 sm:grid-cols-4 md:grid-cols-6 xl:grid-cols-8">{items.map(i=><button key={`${i.media_type}-${i.tmdb_id}`} onClick={()=>open(i)} className="text-left"><div className="aspect-[2/3] overflow-hidden rounded-xl bg-white/10">{i.poster_url?<img src={i.poster_url} className="h-full w-full object-cover"/>:null}</div><p className="mt-2 line-clamp-2 text-xs font-black">{name(i)}</p><p className="text-xs text-white/50">★ {Number(i.rating||0).toFixed(1)} • {i.year||'-'} • {i.watch_url?'พร้อมดู':'ไม่มีลิงก์'}</p></button>)}</div>{hasMore?<div className="mt-6 text-center"><button onClick={()=>load(offset,true)} className="rounded-xl bg-white/10 px-6 py-3 text-sm font-black">โหลดเพิ่ม {limit}</button></div>:null}{active&&form?<Edit item={active} form={form} setForm={setForm} onClose={()=>{setActive(null);setForm(null);}} onSave={save} saving={saving}/>:null}</main>;
}
